// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.27;

import {Test} from "forge-std/Test.sol";

import {Poseidon2} from "../../src/libraries/Poseidon2.sol";

/// Minimal harness so `vm.expectRevert` has a sub-call to bite on
/// (library `internal pure` calls inline into the test, which would
/// otherwise put the revert at the same call depth as the cheatcode).
contract Poseidon2Harness {
    function hash2(uint256 l, uint256 r) external pure returns (bytes32) {
        return Poseidon2.hash2(l, r);
    }
}

/// @notice Day-14c Stage A: pin the Solidity Poseidon2 library against
///         test vectors generated by `code/circuits/scripts/poseidon_vectors/`.
///
///         Each vector is the output of `Poseidon2::hash([l, r], 2)` run
///         under nargo 1.0.0-beta.18 + `poseidon` lib v0.1.1 (which
///         re-exports Noir stdlib's `poseidon2_permutation` foreign
///         function -- the same one every `lib_common::merkle_root`
///         call uses inside our 11 circuits).
///
///         If any vector here breaks, either the circuit-side hash or
///         the Solidity-side hash has drifted, and Stage B's IMT will
///         silently produce roots a circuit-bound proof rejects.
contract Poseidon2Test is Test {
    Poseidon2Harness internal harness;

    function setUp() public {
        harness = new Poseidon2Harness();
    }

    // ----- helper ------------------------------------------------------------

    function _check(uint256 l, uint256 r, bytes32 expected) internal pure {
        bytes32 got = Poseidon2.hash2(l, r);
        require(got == expected, "Poseidon2: vector mismatch");
    }

    // ----- vectors (generated by scripts/poseidon_vectors/) ------------------

    function test_vec_00_zero_zero() public pure {
        _check(0, 0, 0x0b63a53787021a4a962a452c2921b3663aff1ffd8d5510540f8e659e782956f1);
    }

    function test_vec_01_zero_one() public pure {
        _check(0, 1, 0x0dd6d785caa3fe1ad139a40b6bd26fccbd6c8697573b0e34489c740533db5cc8);
    }

    function test_vec_02_one_zero() public pure {
        _check(1, 0, 0x1e05013a2f40c60dc58cfe36bfa4d7e94676c43436922368628342bc5144d103);
    }

    function test_vec_03_one_one() public pure {
        _check(1, 1, 0x1df6080e5bf5cefb3e40daf91cfcc5a267781505471aa058c0b205986774f978);
    }

    function test_vec_04_one_two() public pure {
        _check(1, 2, 0x038682aa1cb5ae4e0a3f13da432a95c77c5c111f6f030faf9cad641ce1ed7383);
    }

    function test_vec_05_two_three() public pure {
        _check(2, 3, 0x2bc00d90b885b09d12764e764410f7f693f514f7f3ca14d916741ff3968b3079);
    }

    function test_vec_06_small_pair() public pure {
        _check(42, 1729, 0x1c19c28fa4d066c2fc922baba534304092c52d0566e72670268bfd47afeda7f1);
    }

    function test_vec_07_keccak_style_pair() public pure {
        _check(
            0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,
            0x0fedcba0987654320fedcba0987654320fedcba0987654320fedcba098765432,
            0x0b357ed8ae39f700c0f713613a8851c6c170dcfc6bfb1f0300a9520c6ee59a09
        );
    }

    function test_vec_08_max_minus_one_pair() public pure {
        // p - 1 and p - 2
        _check(
            0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000,
            0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593efffffff,
            0x2a3af28ae45056e36af2c3a829f1500c199a3f0aa681c199b7366d00676f0ca9
        );
    }

    function test_vec_09_iv_neighborhood() public pure {
        // Stresses lanes around the sponge IV value 2<<64.
        _check(
            0x10000000000000000,
            0x20000000000000000,
            0x05510aa08876d798a1d0061eac844a5602e8d00c4dfc8f41739e843833327763
        );
    }

    function test_vec_10_merkle_left_branch() public pure {
        // Mirrors one merkle_root level: leaf vs zero sibling, left branch.
        _check(
            0x1f7e1b73f1c6a9c11de4fee5e57bcaff0e3a85a7b67afcd3edc8e1f9bbc4d3a2,
            0,
            0x080f70df0e78effd4c9de7467c782528094799110267c05be0d30ebadb3ae184
        );
    }

    function test_vec_11_merkle_right_branch() public pure {
        // Right branch: zero current node, populated sibling.
        _check(
            0,
            0x1f7e1b73f1c6a9c11de4fee5e57bcaff0e3a85a7b67afcd3edc8e1f9bbc4d3a2,
            0x0ec6ebf60b09ba87b23b24bc945c5218f88daa29a8b656476a64969601929ce6
        );
    }

    function test_vec_12_two_commitments() public pure {
        // Internal node above two populated leaves.
        _check(
            0x0a7c3b8f9d4e2c1b6a5f4e3d2c1b0a9f8e7d6c5b4a39281706f5e4d3c2b1a09f,
            0x1b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5061728394a5b6c7d8e9f00,
            0x0ca6ca7b9a6d8c62643ddc73c28238ef52059b012086f0a274421230ac69cc2e
        );
    }

    // ----- guards ------------------------------------------------------------

    function test_revert_when_left_at_prime() public {
        uint256 p = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;
        vm.expectRevert(bytes("Poseidon2: input >= PRIME"));
        harness.hash2(p, 0);
    }

    function test_revert_when_right_at_prime() public {
        uint256 p = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;
        vm.expectRevert(bytes("Poseidon2: input >= PRIME"));
        harness.hash2(0, p);
    }

    function test_commutativity_check() public pure {
        // Sanity: hash2 must be order-sensitive (commitment-binding for
        // the IMT depends on this; if l/r symmetrised it would be a bug).
        bytes32 lr = Poseidon2.hash2(0x01, 0x02);
        bytes32 rl = Poseidon2.hash2(0x02, 0x01);
        require(lr != rl, "Poseidon2: hash unexpectedly commutative");
    }

    // ----- gas snapshot ------------------------------------------------------

    function test_gas_snapshot_single_hash() public {
        // Records gas-per-hash for the IMT bookkeeping: Stage B will
        // call this 20 times per insert, so this number times 20 must
        // stay well below a typical lending-tx budget.
        uint256 g0 = gasleft();
        bytes32 out = Poseidon2.hash2(
            0x0a7c3b8f9d4e2c1b6a5f4e3d2c1b0a9f8e7d6c5b4a39281706f5e4d3c2b1a09f,
            0x1b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5061728394a5b6c7d8e9f00
        );
        uint256 used = g0 - gasleft();
        // out is consumed so the call isn't optimised away.
        require(out != bytes32(0), "Poseidon2: zero output");
        // Loose upper bound -- the reference pure-Solidity port spends
        // ~200k; our inline-assembly port should land under 90k. This
        // gate catches regressions if someone replaces the assembly
        // with naive Field arithmetic.
        require(used < 90_000, "Poseidon2: gas regression > 90k");
        emit log_named_uint("Poseidon2.hash2 gas", used);
    }
}
