[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'cd prover-service && npm ci',
  'cd /app && cd data-api && npm ci'
]

[phases.build]
cmds = [
  'cd prover-service && npm run build',
  'cd /app && cd data-api && npm run build'
]

[start]
cmd = 'cd data-api && npm start'
