/**
 * T-12.3 — Schemas shared.
 *
 * Asserts the SDK-TS types and the SDK-Py pydantic models are BOTH derived
 * from the same `docs/openapi.json` that the data-api server emits. The
 * derivation chain is:
 *
 *   data-api zod schemas
 *       └── scripts/dump-openapi.ts ──► docs/openapi.json
 *                                          │
 *               ┌──────────────────────────┼─────────────────────────┐
 *               ▼                          ▼                         ▼
 *           sdk-ts/src/generated      sdk-py/.../generated      sdk-ts/src/intents
 *           /types.ts (openapi-      /models.py (pydantic)     (imports types)
 *           typescript)
 *
 * The test re-derives both sides from `docs/openapi.json` in-process and
 * compares against the checked-in artifacts byte-for-byte.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

const REPO_ROOT = resolve(__dirname, "../../../..");
const SHARED_SPEC = resolve(REPO_ROOT, "docs/openapi.json");
const DATA_API_SPEC = resolve(REPO_ROOT, "code/backend/data-api/openapi/openapi.json");
const SDK_TS_TYPES = resolve(__dirname, "../src/generated/types.ts");
const SDK_PY_MODELS = resolve(
  REPO_ROOT,
  "code/sdks/sdk-py/src/zenfinance_sdk/generated/models.py",
);

describe("T-12.3 — schema derivation chain", () => {
  it("docs/openapi.json matches the data-api's emitted spec byte-for-byte", () => {
    const docs = readFileSync(SHARED_SPEC, "utf8").trim();
    const dataApi = readFileSync(DATA_API_SPEC, "utf8").trim();
    expect(docs).toBe(dataApi);
  });

  it("sdk-ts/generated/types.ts is reproducible from docs/openapi.json", () => {
    const checked = readFileSync(SDK_TS_TYPES, "utf8");
    const work = mkdtempSync(join(tmpdir(), "t12-3-ts-"));
    const out = join(work, "types.ts");
    // Invoke the openapi-typescript CLI JS entrypoint directly via node so
    // the AST→source formatter + header prelude match byte-for-byte
    // without depending on shell-specific PATH resolution for .cmd shims.
    const cliJs = resolve(
      __dirname,
      "..",
      "node_modules",
      "openapi-typescript",
      "bin",
      "cli.js",
    );
    execFileSync(process.execPath, [cliJs, SHARED_SPEC, "-o", out], {
      stdio: ["ignore", "ignore", "pipe"],
      cwd: resolve(__dirname, ".."),
    });
    const regenerated = readFileSync(out, "utf8");
    expect(regenerated.trim()).toBe(checked.trim());
  }, 60_000);

  it("sdk-py/generated/models.py is reproducible from docs/openapi.json", () => {
    const checked = readFileSync(SDK_PY_MODELS, "utf8");
    const work = mkdtempSync(join(tmpdir(), "t12-3-py-"));
    const out = join(work, "models.py");
    execFileSync("python", [
      "-m",
      "datamodel_code_generator",
      "--input", SHARED_SPEC,
      "--input-file-type", "openapi",
      "--output", out,
      "--output-model-type", "pydantic_v2.BaseModel",
      "--target-python-version", "3.11",
    ], { stdio: ["ignore", "ignore", "pipe"] });
    const regenerated = readFileSync(out, "utf8");
    // datamodel-code-generator embeds a "timestamp" line; strip the
    // header `# generated by datamodel-codegen:` and `#   timestamp:` so
    // the equality test is deterministic across runs.
    const strip = (s: string) =>
      s
        .replace(/^#\s*generated by datamodel-codegen.*$/m, "")
        .replace(/^#\s*timestamp:.*$/m, "")
        .replace(/^#\s*filename:.*$/m, "");
    expect(strip(regenerated).trim()).toBe(strip(checked).trim());
  }, 60_000);
});
